services:
   db:
     image: postgres:16
     restart: always
     env_file:
       - .env
     environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5
 
   nocodb:
     image: nocodb/nocodb:latest
     restart: always
     env_file:
       - .env
     ports:
       - 8666:8080
     volumes:
       - ./data/:/usr/app/data/
     environment:
       - NC_DB=pg://db:5432/${DB_NAME}?u=${DB_USER}&p=${DB_PASSWORD}&d=d1
       - NC_AUTH_JWT_SECRET="569a1821-0a93-45e8-87ab-eb857f20a010"
     depends_on:
       - db